apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: app
  labels:
    app: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      name: sample-app
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: docker.io/altf4llc/fem-kubernetes:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: db-config
          env:
            - name: DB_HOST
              value: postgres-rw
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
